services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change-me}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-change-me}@db:5432/${POSTGRES_DB:-app}
      # CORS: allow your web origin(s)
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:3000}
      PYTHONPATH: /app
    depends_on:
      - db
    ports:
      - "8000:8000"

  web:
    build:
      context: .
      # We want the Dockerfile under frontend/
      dockerfile: frontend/Dockerfile
    environment:
      NEXT_PUBLIC_API_BASE: ${NEXT_PUBLIC_API_BASE:-http://localhost:8000}
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  dbdata:
