"""Add Job and JobRun models

Revision ID: 1117d196c298
Revises: 48f51a85ba28
Create Date: 2025-09-29 01:00:57.448087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1117d196c298'
down_revision: Union[str, Sequence[str], None] = '48f51a85ba28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'error', 'canceled', name='jobrun_status'), nullable=False),
    sa.Column('queued_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('ok_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_runs_job_id'), 'job_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_runs_status'), 'job_runs', ['status'], unique=False)
    op.create_table('job_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('message', sa.String(length=400), nullable=False),
    sa.Column('plus', sa.Integer(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['job_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_events_run_id'), 'job_events', ['run_id'], unique=False)
    op.create_index(op.f('ix_job_events_ts'), 'job_events', ['ts'], unique=False)
    op.create_table('job_run_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('site', sa.Enum('rebaid', 'rebatekey', 'myvipon', name='site_enum'), nullable=False),
    sa.Column('stage', sa.Enum('urls', 'details', name='stage_enum'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'error', 'canceled', name='jobrun_status'), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('ok_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['job_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_run_parts_run_id'), 'job_run_parts', ['run_id'], unique=False)
    op.create_index(op.f('ix_job_run_parts_site'), 'job_run_parts', ['site'], unique=False)
    op.create_index(op.f('ix_job_run_parts_status'), 'job_run_parts', ['status'], unique=False)
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_site'), table_name='jobs')
    op.create_unique_constraint('uq_jobs_name', 'jobs', ['name'])
    op.drop_column('jobs', 'site')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('site', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint('uq_jobs_name', 'jobs', type_='unique')
    op.create_index(op.f('ix_jobs_site'), 'jobs', ['site'], unique=False)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.drop_index(op.f('ix_job_run_parts_status'), table_name='job_run_parts')
    op.drop_index(op.f('ix_job_run_parts_site'), table_name='job_run_parts')
    op.drop_index(op.f('ix_job_run_parts_run_id'), table_name='job_run_parts')
    op.drop_table('job_run_parts')
    op.drop_index(op.f('ix_job_events_ts'), table_name='job_events')
    op.drop_index(op.f('ix_job_events_run_id'), table_name='job_events')
    op.drop_table('job_events')
    op.drop_index(op.f('ix_job_runs_status'), table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_job_id'), table_name='job_runs')
    op.drop_table('job_runs')
    # ### end Alembic commands ###
