"""add sites and products

Revision ID: 4104e507f4ce
Revises: dad2171ed951
Create Date: 2025-09-23 02:58:51.974360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4104e507f4ce'
down_revision: Union[str, Sequence[str], None] = 'dad2171ed951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_name'), 'sites', ['name'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('product_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('amazon_url', sa.Text(), nullable=True),
    sa.Column('amazon_store_url', sa.Text(), nullable=True),
    sa.Column('amazon_store_name', sa.String(length=200), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_url'),
    sa.UniqueConstraint('product_url', name='uq_products_url')
    )
    op.create_index(op.f('ix_products_amazon_store_name'), 'products', ['amazon_store_name'], unique=False)
    op.create_index(op.f('ix_products_amazon_store_url'), 'products', ['amazon_store_url'], unique=False)
    op.create_index(op.f('ix_products_amazon_url'), 'products', ['amazon_url'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_external_id'), 'products', ['external_id'], unique=False)
    op.create_index(op.f('ix_products_first_seen_at'), 'products', ['first_seen_at'], unique=False)
    op.create_index(op.f('ix_products_last_seen_at'), 'products', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_products_site_id'), 'products', ['site_id'], unique=False)
    op.create_index('ix_site_last_seen', 'products', ['site_id', 'last_seen_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_site_last_seen', table_name='products')
    op.drop_index(op.f('ix_products_site_id'), table_name='products')
    op.drop_index(op.f('ix_products_last_seen_at'), table_name='products')
    op.drop_index(op.f('ix_products_first_seen_at'), table_name='products')
    op.drop_index(op.f('ix_products_external_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_amazon_url'), table_name='products')
    op.drop_index(op.f('ix_products_amazon_store_url'), table_name='products')
    op.drop_index(op.f('ix_products_amazon_store_name'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_sites_name'), table_name='sites')
    op.drop_table('sites')
    # ### end Alembic commands ###
